/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int icon2=0x7f020001;
        public static final int icon3=0x7f020002;
        public static final int loading=0x7f020003;
        public static final int logo=0x7f020004;
    }
    public static final class id {
        public static final int Distance=0x7f050003;
        public static final int POI=0x7f050002;
        public static final int POIListView=0x7f050001;
        public static final int progress_large=0x01010000;
        public static final int searching=0x7f050000;
    }
    public static final class layout {
        public static final int loading=0x7f030000;
        public static final int main=0x7f030001;
        public static final int poiview=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
